# Generated by Django 5.2.3 on 2025-06-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mood Entry', 'verbose_name_plural': 'Mood Entries'},
        ),
        migrations.RenameField(
            model_name='moodentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='moodentry',
            old_name='mood',
            new_name='mood_type',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='mood_score',
            field=models.FloatField(default=0.5, help_text='Numerical representation of mood (0.0 to 1.0, 0.5 is neutral)'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='note',
            field=models.TextField(blank=True, help_text='Optional: A short note or context for this mood entry.', null=True),
        ),
    ]
