from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ReminderViewSet # Import the new ViewSet

# Create a router and register the ReminderViewSet.
router = DefaultRouter()
router.register(r'reminders', ReminderViewSet, basename='reminder')

# Include the URLs generated by the router.
urlpatterns = [
    path('', include(router.urls)),
]
