# Generated by Django 5.2.3 on 2025-06-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
