# Generated by Django 5.2.3 on 2025-06-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_track_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmoodprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='musicmoodprofile',
            name='mood_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='musicmoodprofile',
            name='total_music_minutes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='track',
            name='external_url',
            field=models.URLField(blank=True),
        ),
    ]
