# Generated by Django 5.2.3 on 2025-06-25 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text="User's bio/description")),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone", max_length=100)),
                ('journal_streak', models.IntegerField(default=0, help_text='Current journaling streak in days')),
                ('reminder_enabled', models.BooleanField(default=True, help_text='Whether reminders are enabled')),
                ('spotify_connected', models.BooleanField(default=False, help_text='Whether Spotify is connected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
