# Generated by Django 5.2.3 on 2025-07-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plantpal_leaves',
            field=models.IntegerField(default=0, help_text='PlantPal Leaves balance for premium features'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="User's bio/description", max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone", max_length=50),
        ),
    ]
