# Generated by Django 5.2.3 on 2025-07-07 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'AVATAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_avatars', to='store.storeitem'),
        ),
    ]
