# Generated by Django 5.2.3 on 2025-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plantpal_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
