# Generated by Django 5.2.3 on 2025-07-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Indicates if the user has an active premium membership.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_expiry_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when premium membership expires.', null=True),
        ),
    ]
