# Generated by Django 5.2.3 on 2025-07-09 07:30

from django.db import migrations


def reset_existing_user_leaves(apps, schema_editor):
    """Reset existing users' leaves to 0"""
    User = apps.get_model('accounts', 'User')
    # Update all existing users to have 0 leaves
    User.objects.all().update(plantpal_leaves=0)


def reverse_reset_existing_user_leaves(apps, schema_editor):
    """Reverse: set all users back to 10 leaves"""
    User = apps.get_model('accounts', 'User')
    # Update all users to have 10 leaves (reverse operation)
    User.objects.all().update(plantpal_leaves=10)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_change_default_leaves_to_zero'),
    ]

    operations = [
        migrations.RunPython(reset_existing_user_leaves, reverse_reset_existing_user_leaves),
    ]
