# Generated by Django 5.2.3 on 2025-06-16 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name given to the plant by the user.', max_length=100)),
                ('species', models.CharField(default='Mystery Seedling', help_text='The type or species of the plant.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the plant.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the plant was created.')),
                ('growth_level', models.IntegerField(default=1, help_text='The current growth level of the plant (e.g., 1-10).')),
                ('health', models.IntegerField(default=100, help_text='The current health percentage of the plant (0-100).')),
                ('last_watered', models.DateTimeField(blank=True, help_text='Timestamp of the last time the plant was watered.', null=True)),
                ('last_fertilized', models.DateTimeField(blank=True, help_text='Timestamp of the last time the plant was fertilized.', null=True)),
                ('health_status', models.CharField(default='good', help_text='Current health status of the plant.', max_length=20)),
                ('music_boost_active', models.BooleanField(default=False, help_text='Whether music boost is currently active.')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='When the plant was added (alias for created_at).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the plant was last updated.')),
                ('user', models.ForeignKey(help_text='The user who owns this plant.', on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text="Type of activity (e.g., 'watered', 'fertilized', 'pruned', 'journal_sentiment').", max_length=50)),
                ('note', models.TextField(blank=True, help_text='Optional notes about the activity.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the activity was logged.')),
                ('value', models.FloatField(default=0.0, help_text='An optional numerical value associated with the activity (e.g., mood score).')),
                ('growth_impact', models.FloatField(default=0.0, help_text='How much this action affected growth.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the log entry.')),
                ('plant', models.ForeignKey(help_text='The plant to which this log entry belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='plants.plant')),
            ],
            options={
                'verbose_name': 'Plant Log',
                'verbose_name_plural': 'Plant Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
