# Generated by Django 5.2.3 on 2025-06-24 21:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('succulent', 'Succulent'), ('fern', 'Fern'), ('flowering', 'Flowering Plant'), ('tree', 'Tree'), ('herb', 'Herb'), ('vine', 'Vine')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('growth_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('growth_stage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('health', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('health_score', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], default='good', max_length=20)),
                ('last_watered', models.DateTimeField(blank=True, null=True)),
                ('last_watered_at', models.DateTimeField(blank=True, null=True)),
                ('last_fertilized', models.DateTimeField(blank=True, null=True)),
                ('water_level', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('care_streak', models.IntegerField(default=0, help_text='Number of consecutive days the plant has been cared for')),
                ('last_care_date', models.DateField(blank=True, help_text='Last date any care action was performed', null=True)),
                ('music_boost_active', models.BooleanField(default=False)),
                ('current_mood_influence', models.CharField(default='neutral', max_length=50)),
                ('total_music_minutes', models.IntegerField(default=0, help_text='Total minutes of music listened')),
                ('journal_mood_score', models.FloatField(default=0.5, help_text='Mood score from journal entries (0.0 to 1.0)')),
                ('spotify_mood_score', models.FloatField(default=0.5, help_text='Mood score from Spotify music (0.0 to 1.0)')),
                ('three_d_model_params', models.JSONField(default=dict)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combined_mood_score', models.FloatField(default=0.5, help_text='Weighted average of journal and music mood (0.0 to 1.0)')),
                ('fantasy_params', models.JSONField(blank=True, default=dict, help_text='Parameters for fantasy/creative plant appearance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemorySeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_seeds', to='journal.journalentry')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_seeds', to='plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('watered', 'Watered'), ('fertilized', 'Fertilized'), ('journal_sentiment', 'Journal Sentiment'), ('music_boost', 'Music Boost'), ('mood_update', 'Mood Update'), ('sunshine', 'Sunshine')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('growth_impact', models.FloatField(default=0.0)),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='plants.plant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
