# Generated by Django 5.2.3 on 2025-06-14 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common or given name of the plant.', max_length=100)),
                ('species', models.CharField(blank=True, help_text='The botanical species of the plant (optional).', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True, help_text="The date when this plant was added to the user's collection.")),
                ('user', models.ForeignKey(help_text='The user who owns this plant.', on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Plant',
                'verbose_name_plural': 'User Plants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date and time the log entry was created.')),
                ('note', models.TextField(blank=True, help_text='Any additional notes or observations for this log.')),
                ('watered', models.BooleanField(default=False, help_text='Indicates if the plant was watered in this log entry.')),
                ('fertilized', models.BooleanField(default=False, help_text='Indicates if the plant was fertilized in this log entry.')),
                ('plant', models.ForeignKey(help_text='The plant this log entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='plants.plant')),
            ],
            options={
                'verbose_name': 'Plant Log',
                'verbose_name_plural': 'Plant Logs',
                'ordering': ['-date'],
            },
        ),
    ]
