# Generated by Django 5.2.3 on 2025-07-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this plant is visible to other users'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_care_date',
            field=models.DateField(blank=True, help_text='Last date the plant was cared for', null=True),
        ),
    ]
