# Generated by Django 5.2.3 on 2025-06-16 14:09 (or your actual generation date/time)
import datetime
import django.db.models.deletion
import django.utils.timezone # Ensure this is imported for timezone.now
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterModelOptions(
            name='plantlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plant Log', 'verbose_name_plural': 'Plant Logs'},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='plantlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='plantlog',
            name='fertilized',
        ),
        migrations.RemoveField(
            model_name='plantlog',
            name='watered',
        ),
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time the plant was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='growth_level',
            field=models.IntegerField(default=1, help_text='The current growth level of the plant (e.g., 1-10).'),
        ),
        migrations.AddField(
            model_name='plant',
            name='health',
            field=models.IntegerField(default=100, help_text='The current health percentage of the plant (0-100).'),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_fertilized',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last time the plant was fertilized.', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last time the plant was watered.', null=True),
        ),
        migrations.AddField(
            model_name='plantlog',
            name='activity_type',
            field=models.CharField(default='', help_text="Type of activity (e.g., 'watered', 'fertilized', 'pruned', 'journal_sentiment').", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time the activity was logged.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantlog',
            name='value',
            field=models.FloatField(default=0.0, help_text='An optional numerical value associated with the activity (e.g., mood score).'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='The name given to the plant by the user.', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(default='Mystery Seedling', help_text='The type or species of the plant.', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='note',
            field=models.TextField(blank=True, help_text='Optional notes about the activity.', null=True),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='plant',
            field=models.ForeignKey(help_text='The plant to which this log entry belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='plants.plant'),
        ),
    ]