# Generated by Django 5.2.3 on 2025-06-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_music_boost',
            field=models.DateTimeField(blank=True, help_text='Last time music affected this plant', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='total_music_minutes',
            field=models.IntegerField(default=0, help_text='Total minutes of music that have affected this plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='growth_level',
            field=models.IntegerField(default=1, help_text='The current growth level of the plant (1-10).'),
        ),
        migrations.AlterField(
            model_name='plantlog',
            name='activity_type',
            field=models.CharField(help_text="Type of activity (e.g., 'watered', 'fertilized', 'pruned', 'journal_sentiment', 'music_boost').", max_length=50),
        ),
    ]
