# Generated by Django 5.2.3 on 2025-06-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='combined_mood_score',
            field=models.FloatField(default=0.5, help_text='Weighted average of journal and music mood (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='fantasy_params',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters for fantasy/creative plant appearance'),
        ),
        migrations.AddField(
            model_name='plant',
            name='journal_mood_score',
            field=models.FloatField(default=0.5, help_text='Mood score from journal entries (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='spotify_mood_score',
            field=models.FloatField(default=0.5, help_text='Mood score from Spotify music (0.0 to 1.0)'),
        ),
    ] 