# Generated by Django 5.2.3 on 2025-07-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_is_public_alter_plant_last_care_date'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='decoration',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'DECORATION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants_with_decoration', to='store.storeitem'),
        ),
        migrations.AddField(
            model_name='plant',
            name='pot',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'POT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants_in_pot', to='store.storeitem'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this plant is visible to other users'),
        ),
    ]
