# Generated by Django 5.2.3 on 2025-06-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_comprehensive_plant_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='care_streak',
            field=models.IntegerField(default=0, help_text='Number of consecutive days the plant has been cared for'),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_care_date',
            field=models.DateField(blank=True, help_text='Last date any care action was performed', null=True),
        ),
    ]
