# Generated by Django 5.2.3 on 2025-06-22 20:45

from django.db import migrations, models


def add_care_streak_fields_if_not_exist(apps, schema_editor):
    """Safely add care streak fields if they don't already exist"""
    db_alias = schema_editor.connection.alias
    
    # Check if columns exist before adding them
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='plants_plant' AND column_name IN ('care_streak', 'last_care_date', 'combined_mood_score');
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Add care_streak if it doesn't exist
        if 'care_streak' not in existing_columns:
            cursor.execute('ALTER TABLE plants_plant ADD COLUMN care_streak INTEGER DEFAULT 0 NOT NULL;')
            
        # Add last_care_date if it doesn't exist
        if 'last_care_date' not in existing_columns:
            cursor.execute('ALTER TABLE plants_plant ADD COLUMN last_care_date DATE NULL;')
            
        # Add combined_mood_score if it doesn't exist
        if 'combined_mood_score' not in existing_columns:
            cursor.execute('ALTER TABLE plants_plant ADD COLUMN combined_mood_score DOUBLE PRECISION DEFAULT 0.0 NOT NULL;')


def reverse_care_streak_fields(apps, schema_editor):
    """Remove care streak fields"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('ALTER TABLE plants_plant DROP COLUMN IF EXISTS care_streak;')
        cursor.execute('ALTER TABLE plants_plant DROP COLUMN IF EXISTS last_care_date;')
        cursor.execute('ALTER TABLE plants_plant DROP COLUMN IF EXISTS combined_mood_score;')


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_care_streak_plant_last_care_date'),
    ]

    operations = [
        migrations.RunPython(
            add_care_streak_fields_if_not_exist,
            reverse_care_streak_fields,
        ),
    ]
