# Generated by Django 5.2.3 on 2025-06-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20250623_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='total_music_minutes',
            field=models.IntegerField(default=0, help_text='Total minutes of music listened'),
        ),
    ]
