# Generated by Django 5.2.3 on 2025-07-07 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Package name (e.g., 'Starter Pack')", max_length=100)),
                ('leaves', models.IntegerField(help_text='Number of leaves in this package')),
                ('price', models.IntegerField(help_text='Price in KES')),
                ('description', models.TextField(blank=True, help_text='Package description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this package is available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PremiumPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Package name (e.g., '30 Day Premium')", max_length=100)),
                ('duration_days', models.IntegerField(help_text='Number of premium days')),
                ('price', models.IntegerField(help_text='Price in KES')),
                ('bonus_leaves', models.IntegerField(default=0, help_text='Bonus leaves awarded with this purchase')),
                ('description', models.TextField(blank=True, help_text='Package description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this package is available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('LEAVES', 'Leaf Purchase'), ('PREMIUM', 'Premium Purchase')], default='LEAVES', max_length=20)),
                ('amount', models.IntegerField(help_text='Amount in KES')),
                ('leaves', models.IntegerField(default=0, help_text='Number of leaves purchased')),
                ('premium_days', models.IntegerField(default=0, help_text='Number of premium days purchased')),
                ('phone_number', models.CharField(help_text='M-Pesa phone number', max_length=15)),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='M-Pesa receipt number', max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, help_text='Merchant request ID from M-Pesa', max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, help_text='Checkout request ID from M-Pesa', max_length=100, null=True)),
                ('result_code', models.CharField(blank=True, help_text='M-Pesa result code', max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, help_text='M-Pesa result description', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When transaction was completed', null=True)),
                ('leaf_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.leafpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
                ('premium_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.premiumpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WateringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_spent', models.IntegerField(default=2, help_text='Number of leaves spent')),
                ('water_amount', models.IntegerField(default=20, help_text='Amount of water given')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_waterings', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_transactions', to='plants.plant')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_waterings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
