# Generated by Django 5.2.3 on 2025-07-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Package name (e.g., '30 Day Premium')", max_length=100)),
                ('duration_days', models.IntegerField(help_text='Number of premium days')),
                ('price', models.IntegerField(help_text='Price in KES')),
                ('description', models.TextField(blank=True, help_text='Package description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this package is available for purchase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.RenameField(
            model_name='mpesatransaction',
            old_name='package',
            new_name='leaf_package',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='premium_days',
            field=models.IntegerField(default=0, help_text='Number of premium days purchased'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction_type',
            field=models.CharField(choices=[('LEAVES', 'Leaf Purchase'), ('PREMIUM', 'Premium Purchase')], default='LEAVES', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='leaves',
            field=models.IntegerField(default=0, help_text='Number of leaves purchased'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='premium_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.premiumpackage'),
        ),
    ]
