# Generated by Django 5.2.3 on 2025-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_premiumpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpackage',
            name='bonus_leaves',
            field=models.IntegerField(default=0, help_text='Bonus leaves awarded with this purchase'),
        ),
    ]
