# Generated by Django 5.2.3 on 2025-06-14 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The main text content of the journal entry.')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date and time the entry was created.')),
                ('is_favorite', models.BooleanField(default=False, help_text='Boolean flag indicating if this entry is marked as a user favorite.')),
                ('mood_entry', models.ForeignKey(blank=True, help_text='The associated mood entry, derived from sentiment analysis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='moods.moodentry')),
                ('user', models.ForeignKey(help_text='The user who created this journal entry.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date'],
            },
        ),
    ]
