# Generated by Django 5.2.3 on 2025-06-16 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('moods', '0002_alter_moodentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Whether this entry is marked as a favorite.'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood_entry',
            field=models.ForeignKey(blank=True, help_text='The associated mood entry for this journal entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='moods.moodentry'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='text',
            field=models.TextField(help_text='The main content of the journal entry.'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(help_text='The user who created this journal entry.', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
