# Generated by Django 5.2.3 on 2025-07-07 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('mood_label', models.CharField(default='neutral', max_length=50)),
                ('mood_score', models.FloatField(default=0.5)),
                ('weather_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_seeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory Seed',
                'ordering': ['-created_at'],
            },
        ),
    ]
